'use client';

import { useEffect, useState } from 'react';
import {
  Button,
  Input,
  Modal,
  ModalContent,
  ModalDescription,
  ModalFooter,
  ModalHeader,
  ModalTitle,
  StatusMessage,
} from '@techfusion/ui';
import { Check, Copy, Eye, EyeOff } from 'lucide-react';
import { copyText } from '@/lib/clipboard';
import { enrollMfa, isValidTotp, normalizeTotp, verifyMfaEnrollment, type MfaEnrollment } from '@/lib/mfa-client';
import { mapMfaError } from '@/lib/mfa-errors';

interface MfaEnrollmentDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerateCodes: () => void;
  onThrottled?: () => void;
}

function maskSecret(secret: string): string {
  const groups = secret.match(/.{1,4}/g) ?? [secret];
  const [first, ...rest] = groups;
  return [first, ...rest.map(() => '••••')].join(' ');
}

/**
 * ACC-UX-02C — MFA enrollment. The QR code and setup key come straight from
 * POST /mfa/enroll (the backend returns the plaintext base32 secret exactly
 * once, plus the QR data URL). The secret is masked by default. Enrollment
 * completes only when the user proves possession with a valid TOTP code.
 */
export function MfaEnrollmentDialog({ open, onOpenChange, onGenerateCodes, onThrottled }: MfaEnrollmentDialogProps) {
  const [step, setStep] = useState<'intro' | 'setup' | 'success'>('intro');
  const [enrollment, setEnrollment] = useState<MfaEnrollment | null>(null);
  const [token, setToken] = useState('');
  const [secretRevealed, setSecretRevealed] = useState(false);
  const [secretCopied, setSecretCopied] = useState(false);
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (open) {
      setStep('intro');
      setEnrollment(null);
      setToken('');
      setSecretRevealed(false);
      setSecretCopied(false);
      setError('');
      setSubmitting(false);
    } else {
      setEnrollment(null);
      setToken('');
      setSecretRevealed(false);
      setSecretCopied(false);
      setError('');
      setSubmitting(false);
    }
  }, [open]);

  const begin = async () => {
    setSubmitting(true);
    setError('');
    try {
      const result = await enrollMfa();
      setEnrollment(result);
      setSecretRevealed(false);
      setSecretCopied(false);
      setStep('setup');
    } catch (e) {
      const mapped = mapMfaError(e);
      if (mapped.kind === 'throttled') onThrottled?.();
      setError(mapped.message);
    } finally {
      setSubmitting(false);
    }
  };

  const verify = async () => {
    if (!isValidTotp(token)) {
      setError('Enter the 6-digit code from your authenticator app.');
      return;
    }
    setSubmitting(true);
    setError('');
    try {
      await verifyMfaEnrollment(token);
      setToken('');
      setStep('success');
    } catch (e) {
      const mapped = mapMfaError(e);
      if (mapped.kind === 'throttled') onThrottled?.();
      setError(mapped.message);
    } finally {
      setSubmitting(false);
    }
  };

  const copySecret = async () => {
    if (!enrollment) return;
    const ok = await copyText(enrollment.secret);
    if (!ok) return;
    setSecretCopied(true);
    window.setTimeout(() => setSecretCopied(false), 2000);
  };

  return (
    <Modal open={open} onOpenChange={onOpenChange}>
      <ModalContent size="lg">
        <ModalHeader>
          <ModalTitle>
            {step === 'setup'
              ? 'Scan the QR code'
              : step === 'success'
                ? 'Two-factor authentication enabled'
                : 'Set up two-factor authentication'}
          </ModalTitle>
          <ModalDescription>
            {step === 'setup'
              ? 'Open your authenticator app, then scan the QR code or enter the setup key manually.'
              : step === 'success'
                ? 'Your account is now protected by a second factor.'
                : 'You will sign in with your password and a one-time code from your authenticator app.'}
          </ModalDescription>
        </ModalHeader>

        {step === 'intro' ? (
          <div className="space-y-3 text-sm text-text-secondary">
            <p>
              Two-factor authentication adds a second step to sign-in: after your password, you
              enter a one-time code generated by an authenticator app on your device.
            </p>
            <ul className="list-disc space-y-1 pl-5">
              <li>Your authenticator app will generate time-based codes.</li>
              <li>You will verify this app once before it is enabled.</li>
              <li>After enabling, generate recovery codes so you can regain access if you lose your app.</li>
            </ul>
            {error && (
              <StatusMessage variant="error" layout="block">
                {error}
              </StatusMessage>
            )}
          </div>
        ) : step === 'setup' && enrollment ? (
          <div className="space-y-4">
            <div className="flex flex-col gap-4 sm:flex-row">
              <div className="flex flex-col items-center gap-2">
                <img
                  src={enrollment.qrCode}
                  alt="QR code to scan with your authenticator app"
                  width={176}
                  height={176}
                  className="h-44 w-44 rounded-lg border border-border bg-white p-1"
                />
                <p className="text-center text-xs text-text-muted">
                  Scan with Google Authenticator, Microsoft Authenticator, or a compatible app.
                </p>
              </div>

              <div className="flex-1 space-y-3">
                <div>
                  <p className="text-xs font-medium text-text-secondary">Setup key</p>
                  <div className="mt-1.5 flex flex-wrap items-center gap-2">
                    <code
                      className="rounded-lg border border-border bg-surface-subtle px-3 py-1.5 text-sm text-text-primary"
                      data-testid="setup-key"
                    >
                      {secretRevealed ? enrollment.secret : maskSecret(enrollment.secret)}
                    </code>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSecretRevealed((v) => !v)}
                      aria-pressed={secretRevealed}
                    >
                      {secretRevealed ? (
                        <EyeOff className="mr-1.5 h-3.5 w-3.5" />
                      ) : (
                        <Eye className="mr-1.5 h-3.5 w-3.5" />
                      )}
                      {secretRevealed ? 'Hide' : 'Show'}
                    </Button>
                    <Button variant="ghost" size="sm" onClick={copySecret} className="gap-1">
                      {secretCopied ? (
                        <Check className="h-3.5 w-3.5 text-success" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                      {secretCopied ? 'Copied' : 'Copy'}
                    </Button>
                  </div>
                  <p className="mt-1.5 text-xs text-text-muted">
                    Enter this key manually if your app cannot scan the QR code.
                  </p>
                </div>

                <Input
                  id="enroll-totp"
                  label="Verification code"
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  maxLength={6}
                  placeholder="123456"
                  value={token}
                  onChange={(e) => setToken(normalizeTotp(e.target.value))}
                  disabled={submitting}
                />
              </div>
            </div>

            {error && (
              <StatusMessage variant="error" layout="block">
                {error}
              </StatusMessage>
            )}
          </div>
        ) : (
          <div className="space-y-3">
            <StatusMessage variant="success" layout="block">
              Two-factor authentication is now enabled.
            </StatusMessage>
            <p className="text-sm text-text-secondary">
              If you ever lose access to your authenticator app, recovery codes are the only way
              back into your account. Generate them now — each code is shown exactly once.
            </p>
          </div>
        )}

        <ModalFooter>
          {step === 'intro' ? (
            <>
              <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)} disabled={submitting}>
                Cancel
              </Button>
              <Button variant="primary" size="sm" onClick={begin} loading={submitting}>
                Continue
              </Button>
            </>
          ) : step === 'setup' ? (
            <>
              <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)} disabled={submitting}>
                Cancel
              </Button>
              <Button variant="primary" size="sm" onClick={verify} loading={submitting}>
                Verify and enable
              </Button>
            </>
          ) : (
            <>
              <Button variant="ghost" size="sm" onClick={() => onOpenChange(false)}>
                Close
              </Button>
              <Button
                variant="primary"
                size="sm"
                onClick={() => {
                  onOpenChange(false);
                  onGenerateCodes();
                }}
              >
                Generate recovery codes now
              </Button>
            </>
          )}
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
}
