import { Injectable } from '@nestjs/common';
import { IReportGenerator, ReportData } from './report-generator.interface';

@Injectable()
export class HtmlGeneratorService implements IReportGenerator {
  readonly format = 'html';

  async generate(data: ReportData): Promise<Buffer> {
    const accent = data.branding.accentColor || '#3b82f6';
    const company = data.branding.companyName || data.orgName;

    const scoreSection = data.scoreData?.length
      ? `
        <h2>Key Scores</h2>
        <div class="scores">
          ${data.scoreData.map((s) => `
            <div class="score-item">
              <span class="score-value" style="color:${accent}">${Math.round(s.value)}${s.max ? '/' + s.max : ''}</span>
              <span class="score-label">${s.label}</span>
            </div>
          `).join('')}
        </div>`
      : '';

    const findingsSection = data.findingsSummary?.length
      ? `
        <h2>Findings Summary</h2>
        <table>
          <tr><th>Severity</th><th>Count</th></tr>
          ${data.findingsSummary.map((f) => `
            <tr>
              <td class="sev-${f.severity || 'none'}">${f.label}</td>
              <td>${f.count}</td>
            </tr>`).join('')}
        </table>`
      : '';

    const aiSection = data.aiSummary
      ? `<h2>Executive Summary</h2><div class="ai-summary"><p>${data.aiSummary}</p></div>`
      : '';

    const sectionsHtml = data.sections
      .map(
        (s) => `
        <div class="section">
          <h2>${s.title}</h2>
          <p>${s.content}</p>
          ${s.subSections?.map((ss) => `
            <div class="sub-section">
              <h3>${ss.title}</h3>
              <p>${ss.content}</p>
            </div>`).join('') || ''}
        </div>`,
      )
      .join('');

    const metaRows = data.metadata
      ? Object.entries(data.metadata)
          .map(([k, v]) => `<tr><td class="meta-key">${k}</td><td>${v}</td></tr>`)
          .join('')
      : '';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${data.title} - ${company}</title>
<style>
  @page { margin: 20mm 15mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1f2937; line-height: 1.5; font-size: 11pt; margin:0; padding:20px; }
  .header { border-bottom: 3px solid ${accent}; padding-bottom: 10px; margin-bottom: 20px; }
  .header h1 { margin:0; font-size: 20pt; color: #111827; }
  .header .meta { color: #6b7280; font-size: 9pt; margin-top: 4px; }
  h2 { color: ${accent}; font-size: 13pt; margin-top: 20px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  h3 { color: #374151; font-size: 11pt; margin-top: 12px; }
  p { margin: 6px 0; }
  table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 10pt; }
  th { background: #f3f4f6; padding: 6px 8px; text-align: left; border: 1px solid #e5e7eb; }
  td { padding: 6px 8px; border: 1px solid #e5e7eb; }
  .scores { display: flex; gap: 12px; margin: 10px 0; flex-wrap: wrap; }
  .score-item { flex: 1; min-width: 100px; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; text-align: center; }
  .score-value { font-size: 24pt; font-weight: 700; display: block; }
  .score-label { font-size: 8pt; color: #6b7280; text-transform: uppercase; margin-top: 2px; }
  .ai-summary { background: #f0f7ff; border-left: 4px solid ${accent}; padding: 12px; margin: 10px 0; border-radius: 4px; }
  .section { margin: 10px 0; }
  .sub-section { margin: 8px 0 8px 16px; padding: 8px; background: #fafafa; border-radius: 4px; }
  .sev-critical { color: #dc2626; font-weight: 600; }
  .sev-high { color: #ea580c; font-weight: 600; }
  .sev-medium { color: #ca8a04; font-weight: 600; }
  .sev-low { color: #16a34a; }
  .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e7eb; font-size: 8pt; color: #9ca3af; text-align: center; }
  .meta-table { width: auto; }
  .meta-key { font-weight: 600; color: #374151; width: 140px; }
</style>
</head>
<body>
<div class="header">
  <h1>${data.title}</h1>
  <div class="meta">
    ${company} | ${new Date(data.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
    ${data.deviceName ? ' | ' + data.deviceName : ''}
  </div>
</div>
${metaRows ? '<table class="meta-table">' + metaRows + '</table>' : ''}
${scoreSection}
${findingsSection}
${aiSection}
${sectionsHtml}
<div class="footer">Generated by TechFusion AI | Confidential</div>
</body></html>`;

    return Buffer.from(html, 'utf-8');
  }
}
