import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { IReportGenerator, ReportData } from './report-generator.interface';

@Injectable()
export class PdfGeneratorService implements IReportGenerator {
  readonly format = 'pdf';

  async generate(data: ReportData): Promise<Buffer> {
    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const accent = data.branding.accentColor || '#3b82f6';
      const company = data.branding.companyName || data.orgName;

      const L = 50;
      let top = 50;

      // Header
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#111827').text(data.title, L, top, { width: 495 });
      top += 28;
      doc.fontSize(9).font('Helvetica').fillColor('#6b7280').text(
        `${company} | ${new Date(data.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}${data.deviceName ? ' | ' + data.deviceName : ''}`,
        L, top,
      );
      top += 16;
      doc.moveTo(L, top).lineTo(545, top).strokeColor(accent).lineWidth(2).stroke();
      top += 16;

      // Metadata
      if (data.metadata) {
        doc.fontSize(8).fillColor('#374151');
        for (const [key, val] of Object.entries(data.metadata)) {
          doc.font('Helvetica-Bold').text(`${key}: `, L, top, { continued: true, width: 120 });
          doc.font('Helvetica').text(val, { width: 375 });
          top += 12;
          if (top > 750) { doc.addPage(); top = 50; }
        }
        top += 8;
      }

      // Scores
      if (data.scoreData?.length) {
        doc.fontSize(13).font('Helvetica-Bold').fillColor(accent).text('Key Scores', L, top);
        top += 20;
        for (const s of data.scoreData) {
          if (top > 740) { doc.addPage(); top = 50; }
          const x = L + 10;
          doc.roundedRect(x, top, 110, 50, 6).fillAndStroke('#f3f4f6', '#e5e7eb');
          doc.fillColor('#111827').fontSize(22).font('Helvetica-Bold').text(
            Math.round(s.value).toString(), x + 10, top + 6, { width: 90, align: 'center' },
          );
          doc.fillColor('#6b7280').fontSize(7).font('Helvetica').text(
            s.label.toUpperCase(), x + 10, top + 34, { width: 90, align: 'center' },
          );
          top += 60;
        }
        top += 8;
      }

      // Findings summary
      if (data.findingsSummary?.length) {
        if (top > 730) { doc.addPage(); top = 50; }
        doc.fontSize(13).font('Helvetica-Bold').fillColor(accent).text('Findings Summary', L, top);
        top += 20;
        for (const f of data.findingsSummary) {
          if (top > 740) { doc.addPage(); top = 50; }
          doc.fontSize(9).fillColor('#374151')
            .font('Helvetica-Bold').text(f.label, L + 10, top, { width: 120 })
            .font('Helvetica').text(f.count.toString(), 200, top);
          top += 14;
        }
        top += 8;
      }

      // AI Summary
      if (data.aiSummary) {
        if (top > 710) { doc.addPage(); top = 50; }
        doc.fontSize(13).font('Helvetica-Bold').fillColor(accent).text('Executive Summary', L, top);
        top += 20;
        doc.roundedRect(L, top, 495, 60, 4).fillAndStroke('#f0f7ff', accent);
        doc.fillColor('#374151').fontSize(9).font('Helvetica').text(data.aiSummary, L + 10, top + 8, { width: 475 });
        top += 76;
      }

      // Sections
      for (const section of data.sections) {
        if (top > 690) { doc.addPage(); top = 50; }
        doc.fontSize(13).font('Helvetica-Bold').fillColor(accent).text(section.title, L, top);
        top += 18;
        doc.fontSize(9).font('Helvetica').fillColor('#374151').text(section.content, L, top, { width: 495 });
        top += doc.heightOfString(section.content, { width: 495 }) + 8;

        if (section.subSections) {
          for (const ss of section.subSections) {
            if (top > 710) { doc.addPage(); top = 50; }
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text(ss.title, L + 10, top);
            top += 14;
            doc.fontSize(9).font('Helvetica').fillColor('#4b5563').text(ss.content, L + 10, top, { width: 475 });
            top += doc.heightOfString(ss.content, { width: 475 }) + 8;
          }
        }
        top += 6;
      }

      // Footer
      doc.fontSize(7).fillColor('#9ca3af').text(
        'Generated by TechFusion AI | Confidential',
        L, 780, { width: 495, align: 'center' },
      );

      doc.end();
    });
  }
}
